from yacs.config import CfgNode as CN

_C = CN()

# -----------------------------------------------------------------------------
# MODEL
# -----------------------------------------------------------------------------
_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda:0"
_C.MODEL.META_ARCHITECTURE = "SAM"
_C.MODEL.PRETRAIN = True
_C.MODEL.PRETRAIN_PATH = ""
_C.MODEL.IS_STRICT = False
_C.MODEL.PIXEL_MEAN = [0.485*255, 0.456*255, 0.406*255]
_C.MODEL.PIXEL_STD = [0.229*255, 0.224*255, 0.225*255]

_C.MODEL.IMAGE_ENCODER = CN()
_C.MODEL.IMAGE_ENCODER.NAME = "ImageEncoderViT"
_C.MODEL.IMAGE_ENCODER.ENCODER_DEPTH = 12
_C.MODEL.IMAGE_ENCODER.ENCODER_EMBED_DIM = 768
_C.MODEL.IMAGE_ENCODER.IMAGE_SIZE = 1024
_C.MODEL.IMAGE_ENCODER.MPL_RATIO = 4
_C.MODEL.IMAGE_ENCODER.NUM_HEADS = 12
_C.MODEL.IMAGE_ENCODER.PATCH_SIZE = 16
_C.MODEL.IMAGE_ENCODER.QKV_BIAS = True
_C.MODEL.IMAGE_ENCODER.USE_REL_POS = True
_C.MODEL.IMAGE_ENCODER.GLOBAL_ATTN_INDEXES = [2, 5, 8, 11]
_C.MODEL.IMAGE_ENCODER.WINDOW_SIZE = 14
_C.MODEL.IMAGE_ENCODER.OUT_CHANS = 256

_C.MODEL.PROMPT_ENCODER = CN()
_C.MODEL.PROMPT_ENCODER.NAME = "PromptEncoder"
_C.MODEL.PROMPT_ENCODER.EMBED_DIM = 256
_C.MODEL.PROMPT_ENCODER.IMAGE_EMBED_SIZE = (64, 64)
_C.MODEL.PROMPT_ENCODER.INPUT_IMAGE_SIZE = (1024, 1024)
_C.MODEL.PROMPT_ENCODER.MASK_IN_CHANNELS = 16

_C.MODEL.MATTING_DECODER = CN()
_C.MODEL.MATTING_DECODER.NAME = "MaskDecoder"
_C.MODEL.MATTING_DECODER.TRANSFORMER_DEPTH = 2
_C.MODEL.MATTING_DECODER.TRANSFORMER_EMBED_DIM = 256
_C.MODEL.MATTING_DECODER.TRANSFORMER_MLP_DIM = 2048
_C.MODEL.MATTING_DECODER.TRANSFORMER_NUM_HEADS = 8
_C.MODEL.MATTING_DECODER.TRANSFORMER_DIM = 256
_C.MODEL.MATTING_DECODER.TRANSFORMER_IOU_HEAD_DEPTH = 3
_C.MODEL.MATTING_DECODER.TRANSFORMER_IOU_HEAD_HIDDEN_DIM = 256
# -----------------------------------------------------------------------------
# INPUT
# -----------------------------------------------------------------------------
_C.INPUT = CN()
_C.INPUT.SIZE_IMAGE = [1024, 1024]
